language: generic
sudo: true
before_deploy:
- mpy-cross motor.py
- mpy-cross pca9685.py
- mpy-cross servo.py
- mpy-cross stepper.py
before_install:
- sudo apt-get -yqq update
- sudo apt-get install -y build-essential git python
- git clone https://github.com/adafruit/micropython.git
- make -C micropython/mpy-cross
- export PATH=$PATH:$PWD/micropython/mpy-cross/
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - "motor.mpy"
  - "pca9685.mpy"
  - "servo.mpy"
  - "stepper.mpy"
  skip_cleanup: true
  on:
    tags: true
